### ISSUE TITLE
Once a subscription is created, the plugin should post the subscription ID and info to the channel

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-servicenow#116]
Once a subscription is created, the plugin should post the subscription ID and info to the channel. This is typical of other integrations. This could either be a post in the channel by the bot or just an ephemeral post to the user creating the subscription. 

Currently nothing happens after a subscription save.

This serves to provide feedback that the subscription was created successfully and also shows the ID in case I want to go make an edit right after saving.

**note**: This is somewhat lower impact on SN as subscriptions are shown in the RHS as well as the `list` command.

**Comment by DHaussermann** [comment]
@manojmalik20 just posting for visibility that this is **not** resolved by https://github.com/Brightscout/mattermost-plugin-servicenow/pull/121 Keeping issue open. 

To be explicit I **don't** see this being a blocking issue.

**Comment by ayusht2810** [comment]
@DHaussermann fixed in PR https://github.com/mattermost/mattermost-plugin-servicenow/pull/169. Please verify

**Comment by raghavaggarwal2308** [comment]
@mickmister @DHaussermann Can we close this issue?

**Comment by mickmister** [comment]
> Can we close this issue?

@raghavaggarwal2308 It looks like the PR is still open
