### ISSUE TITLE
Create a user-friendly page to display when user authenticates but email does not match

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-servicenow#139]
When a user tries to connect and authenticates but the email from Mattermost does **not** match the email in Service Now, the user see's an error. 

The user should see a friendlier error for this.  

![image](https://user-images.githubusercontent.com/35588783/206296033-f6aefa5b-1c37-455b-b0e2-941a51c55f89.png)

**Comment by manojmalik20** [comment]
@DHaussermann Is it okay to send a DM to the user from the bot showing a friendly error? OR do we have to create a separate page?

**Comment by mickmister** [comment]
@manojmalik20 @DHaussermann We typically don't curate these pages too much. Maybe just change this text to "Please make sure your email address on your Mattermost account matches the email in your ServiceNow account."

**Comment by ayusht2810** [comment]
@DHaussermann fixed the issue in PR https://github.com/mattermost/mattermost-plugin-servicenow/pull/170. Please review

**Comment by raghavaggarwal2308** [comment]
@mickmister @DHaussermann Can we close this issue?
