### ISSUE TITLE
`/servicenow subscriptions add` is not opening the modal as expected

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-servicenow#140]
There seems to be an issue on some servers where the modal for adding a subscription will not open. Nothing happens when you run the slash command. I see nothing relevant in browser dev logs or console logs.

The modal does open with the Add New subscription button. 

https://user-images.githubusercontent.com/35588783/206378678-d6d5598d-951f-4384-9945-306b0b20e1ea.mov

- This occurs on a cloud server I have running `5.37.3` I do not see the same issue occur locally.
- Both servers are running the `v2.3.3` build from the version bump PR in this repo. 
- This occurs in all browsers and the desktop client.

**Comment by ayusht2810** [comment]
@DHaussermann this issue will be fixed with issue #120

**Comment by DHaussermann** [comment]
@ayusht2810 are you able to provide some context on why my other server is not affected? 

Was it possible to open a modal with the command on earlier builds before `v2.3.3`?

**Comment by DHaussermann** [comment]
@ayusht2810 after discussing this issue it could be lower in priority however on the `5.37` server in the video - There is no button to add additional subscriptions beyond the 1st once 1 is created. 
![image](https://user-images.githubusercontent.com/35588783/206550695-d531fa08-7129-408c-a549-ffa0888505aa.png)

This also does not repro on my local. Ping me if it helps to send an invite to the affected server. Also happy to open a separate issue here if neded.

**Comment by DHaussermann** [comment]
@ayusht2810 I also see this issue on the `Add` and `Update`  buttons can you see if this is the same probem 

![image](https://user-images.githubusercontent.com/35588783/207070619-321385b5-3235-4b90-9de7-23501e4a2680.png)

**Comment by ayusht2810** [comment]
@DHaussermann this issue is fixed in the PR https://github.com/mattermost/mattermost-plugin-servicenow/pull/141

**Comment by ayusht2810** [comment]
@DHaussermann These are fixed so please verify and close

**Comment by ayusht2810** [comment]
@DHaussermann reminder to verify the issue.

**Comment by raghavaggarwal2308** [comment]
@ayusht2810 Verified, the above issue are fixed now.

Tested on MM cloud server version v5.37.3 with master branch
