### ISSUE TITLE
Security: Potential DoS in Search API

### ISSUE THREAD

**Issue by asatkinson** [mattermost/mattermost-plugin-servicenow#145]
#### Description
The ServiceNow plugin does not has any upper limit of perPage param in the Search Records API. The default results per page is 10,000 as found in this [link](https://www.servicenow.com/community/developer-forum/what-is-the-limit-for-results-on-rest-table-api/m-p/1587156). Increasing the perPage parameter in the plugin request to 10,000 can cause performance implications and crash the plugin. 

### Impact
A bad actor can increase this value to a potentially higher number (upto 10k records) and cause performance implications/Denial of Service. 

--------------------------

**Comment by ayusht2810** [comment]
@asatkinson This security issue is already fixed. Please confirm and close this issue.

**Comment by raghavaggarwal2308** [comment]
Closing as already fixed
