### ISSUE TITLE
Security: Plugin allows a subscription to be created on behalf of an another user

### ISSUE THREAD

**Issue by asatkinson** [mattermost/mattermost-plugin-servicenow#146]
#### Description
The Create/Update Subscription API endpoints of the ServiceNow plugin does not have any proper checks in place to verify if the user_id sent in the request is same as authenticated user or not. 

### Impact
A bad actor can modify the user_id sent in the body params of the Create/Update API endpoints and thereby alter the integrity of the creator of the subscription. When such request is sent, the plugin displays that the subscription was created by the other user.

**Comment by ayusht2810** [comment]
@asatkinson These are fixed so please verify and close

**Comment by ayusht2810** [comment]
@mickmister the issue is fixed. Please verify and close

**Comment by mickmister** [comment]
Fixed with https://github.com/mattermost/mattermost-plugin-servicenow/pull/151
