### ISSUE TITLE
ServiceNow Plugin is vulnerable to Blind SSRF

### ISSUE THREAD

**Issue by asatkinson** [mattermost/mattermost-plugin-servicenow#148]
#### Description
On a cloud instance, is the ServiceNow URL is set to say http://localhost:8061 and then if any request is made to any of the ServiceNow Plugin APIs, for example say, `search for records`, the plugin responds back with an error message which looks like this:

```
"Error in searching for records in ServiceNow. Error: Get \"http://localhost:8061/api/now/table/incident?sysparm_fields=sys_id%2Cnumber%2Cshort_description&sysparm_limit=20&sysparm_offset=0&sysparm_query=short_description+LIKETEs+%5EOR+number+STARTSWITHTEs\": Post \"http://localhost:8061/oauth_token.do\": dial tcp [::1]:8061: connect: connection refused"
```

### Impact
From the response, the attacker can easily scan different ports open on the system and perform a Blind SSRF attack.

**Comment by ayusht2810** [comment]
@asatkinson These are fixed so please verify and close

**Comment by ayusht2810** [comment]
@mickmister the issue is fixed. Please verify and close

**Comment by mickmister** [comment]
Fixed with https://github.com/mattermost/mattermost-plugin-servicenow/pull/151
