### ISSUE TITLE
ServiceNow Config is exposed to all Mattermost users

### ISSUE THREAD

**Issue by asatkinson** [mattermost/mattermost-plugin-servicenow#149]
#### Description
When a ServiceNow Plugin is installed and configured, a regular Mattermost user who has not connected their ServiceNow account, is allowed to make a request and fetch all the ServiceNow configurations via `/plugins/mattermost-plugin-servicenow/api/v1/config` API endpoint. This API endpoint responds back with sensitive configurations like ServiceNowOAuthClientID, ServiceNowOAuthClientSecret, EncryptionSecret, WebhookSecret. 

### Impact
Any Mattermost user, including Guest Users, can fetch this information and use it to send Phishing Notifications to the subscribed channels. Alternatively, the user can also use this information and create tampered OAuth requests. 

### Suggested Fix
This configuration is only used in the System Console and hence only a system admin should be allowed to request this API endpoint.

**Comment by ayusht2810** [comment]
@asatkinson These are fixed so please verify and close

**Comment by ayusht2810** [comment]
@mickmister the issue is fixed. Please verify and close
