### ISSUE TITLE
Add documentation about how to use the `/servicenow search` command (and make hint for usage)

### ISSUE THREAD

**Issue by brittanynavin** [mattermost/mattermost-plugin-servicenow#185]
I am unable to understand how to use the `/servicenow search` slash command after reading through your documentation. There are no usage examples in the documentation and no hint is displayed in Mattermost when you type `/servicenow search`.

![image](https://github.com/mattermost/mattermost-plugin-servicenow/assets/4966770/86e9da98-a46f-48dc-a45e-a9efd2c30b59)
![image](https://github.com/mattermost/mattermost-plugin-servicenow/assets/4966770/5ad6688f-8f56-41f1-9d62-0fddb94ed49e)

**Comment by Kshitij-Katiyar** [comment]
@brittanynavin Just run the '/servicenow search' command without any parameters and it will open a modal containing 2 fields
1) Record Type: Here you can select the type of record you want to search 
2) Search Box: Here you have to type at least 3 letters to search your record. 
![Screenshot from 2024-03-15 20-20-14](https://github.com/mattermost/mattermost-plugin-servicenow/assets/90389917/aae6286d-988e-4aa9-99ad-cca990fa1128)

Please let me know if you want anything else.
