### ISSUE TITLE
Set channels which subscriptions cannot be added to

### ISSUE THREAD

**Issue by brittanynavin** [mattermost/mattermost-plugin-servicenow#187]
Add the ability for admins to remove channels which they do not want subscriptions to be added to (for example the ~general channel which could have thousands of users)

**Comment by Kshitij-Katiyar** [comment]
@mickmister Is there any need for this feature as of now?

**Comment by mickmister** [comment]
Hi @brittanynavin, thanks for filing this issue :+1:

This feature is a good idea, but it seems a niche, and potentially inconvenient to configure. Closing as "not planned". Thanks @Kshitij-Katiyar
